export const data = [
  {
    name: "Ponzi",
    image: "/Ponzi.png",
    header: "Ponzi Scheme",
    body: "So your friends made money from DECI and other Ponzi schemes, and despite your better judgement you decided not to send that 100K to mathe just yet. I mean, a 200% return on investment in two months? Who wouldn’t jump at the opportunity!? Boom! You put in your savings, Bang!, Their offices are closed! F*^% ! The money disappears as fast as you thought you would triple it.",
  },
  {
    name: "Pastor",
    image: "/Pastor.png",
    header: "Pastor",
    body: "Your pastor and his wife have his and hers range rover. You still haggle in the matatu about the fare to church. He takes your money; you hold on to faith. Everyday in church there is a fundraiser to buy your spiritual leader things too good for mere mortals such as yourself to experience. Anyway, Hope is currency and your weekly keshas are investment accounts eh?",
  },
  {
    name: "Luthuli",
    image: "/Luthuli.png",
    header: "Luthuli Avenue",
    body: "When you go to Luthuli Avenue to buy a TV you will come out with a certificate from the ”Society Of Goods Reappropriation Professionals” . Walk down the street with that fancy new laptop, still in the box and these wonderful chaps will help relieve you of your burden, and maybe your wallet too. Don’t worry though, they often give back just enough money for you to get home.",
  },
  {
    name: "WashWash",
    image: "/WashWash.png",
    header: "Wash Wash",
    body: "Turn money into more money. A man who is not even your pastor or saviour reborn (again) will miraculously turn funny coloured paper into money! He’s got a fancy suit and more bling than Atwoli and Mike Sonko at a Dubai jewellery expo.. You give him legit money. He buys special chemicals and dips the funny coloured paper in it. Suddenly your money has doubled! Now you completely believe him! He needs more money for more chemicals to make more fake money! Then…then he stops taking your calls.",
  },
  {
    name: "Nywele",
    image: "/shuka.png",
    header: "AKI BEB NITUMIE YA NYWELE",
    body: "Her hair is always on fleek, mainly because her blesser (read: You) is always taking care of her hair. However, hair maintenance doesn’t cost a fraction of what you send her. You’re just an ATM with a receding hairline.",
  },
  {
    name: "Ben10",
    image: "/ben10.png",
    header: "BEN 10 WA AUNTY WA HARRIER",
    body: "He has no job yet, everything is always JUST about to work out. Until then, however, he drives his girlfriend’s harrier around the city to hit up his friends and hit on her girlfriends.",
  },
  {
    name: "IPhoneXL",
    image: "/HAND.png",
    header: "IPHONE XL (SHHH! KWA BEI YA CHINI)",
    body: "Nothing sounds as good as getting premium electronics on the cheap. Sure, the IPhone usually costs about KSh 50 000 more but this guy, in a back alley seems trustworthy? Right? Well, soon as he’s left with your money in hand you’ll find out that all you’ve got is a phone casing filled with mud, a double AA battery and a few lights.",
  },
  {
    name: "Shitstorm",
    image: "/streetboy.png",
    header: "SHITSTORM MEETS WHITE PANTS",
    body: "They patrol Nairobi’s street like a roving pack of predators. Looking for unsuspecting victims, their weapon in hand. On particularly hot days, it becomes more potent. They spot you one day, dressed in white, on your way to meet your date. Three surround you and open their hands. Inside each palm is faecal matter, human or dog, you can’t tell. But the street kids’ demands aren’t unclear. It’s a shitty shakedown for shillings. You empty your pockets into an empty palm and they slip away. I guess the date is cancelled now, ay?",
  },
  {
    name: "FakeLogBook",
    image: "/LOGBOOK.png",
    header: "FAKE LOGBOOK",
    body: "You’ve saved up for years. Butter is a luxury you only see on the television. However, it was worth it, finally you’ve bought the car you’ve always wanted. What’s more, the guy even gave you a discount if you paid in cash! However, before you can even replace that new car smell with your own brand of funk, a car pulls up in front of you on the highway and three burly men pop out and rush towards you. Your car is up for auction, some clever monkey has cloned your log book and used it as security to take out loans from every single digital loan app, SACCO and dodgy logbook loan office on river road .",
  },
  {
    name: "House Off plan",
    image: "/house.png",
    header: "BUYING A HOUSE OFF PLAN",
    body: "You’ve saved up for years. Butter is a luxury you only see on the television. However, it was worth it, finally you’ve bought the car you’ve always wanted. What’s more, the guy even gave you a discount if you paid in cash! However, before you can even replace that new car smell with your own brand of funk, a car pulls up in front of you on the highway and three burly men pop out and rush towards you. Your car is up for auction, some clever monkey has cloned your log book and used it as security to take out loans from every single digital loan app, SACCO and dodgy logbook loan office on river road .",
  },
  {
    name: "Multi-level Marketing",
    image: "/multilevel.png",
    header: "MULTILEVEL MARKETING",
    body: "Your friend calls you and asks you to join her for a wonderful conference and business opportunity. Plus, there’s a free lunch! So you join her at the Pan Africa conference room and the guy I’m stage starts with “WHO WANTS TO MAKE SOME MONEY!” Well you do, of course! So you lay forthe Ksh 5000 application fee and they tell you that all you need to do is recruit more people, who will recruit more people. The more people recruited under you the more money you make. It take you about an hour later before you realise that basically it’s a pyramid.",
  },
  {
    name: "Pata Potea",
    image: "/patapotea.png",
    header: "PATA POTEA",
    body: "You are walking in town minding your own business, then you see some guys crowded at one spot, since you’re waiting for that relative from shags who your mother insists on you picking from Tearoom, you decide to join the crowd. People are winning off a very easy game, so you decide that bus fare your mum gave you, you’d bet it on the card guys, ole wako kumbe it was all a sham to begin with. Let’s just say it ends in premium tears.",
  },
  {
    name: "Newspaper in a matatu",
    image: "/newspaper.png",
    header: "NEWSPAPER IN A  MATATU",
    body: "That guy reading a newspaper in the mat, looks harmless, yes? NO! Nobody cares about the news that much, the guy at the front farted and you can almost see the small in the air but Mr newspaper has not even reacted. As you suffer the gastric attack, the hand not holding the newspaper reaches into your bag and takes out your wallet and phone. Once he’s done he finally notices the smell and starts fanning his face with the newspaper before he gets off at the next stop.",
  },
  {
    name: "Biz",
    image: "/biz.png",
    header: "NAANZA BIZ",
    body: "Your buddy has attended all the right seminars, downloaded business plan templates off the internet and is now ready to start a new business…again. If you invest with him he promises that your bank account will soon become more swollen than Charlie SHeen’s liver. You believe in him, you trust him, you’ve known each other for years! So you make the transfer to his bank account and the next day he’s converted all the money you gave him into champagne for Njeri, Atieno, Nyasuguta and every other person with five metres of him at B-Club.",
  },
  {
    name: "Vote",
    image: "/vote.png",
    header: "VOTE FOR ME",
    body: "Your neighbourhood looks like a warzone, the local government officials spend their time buying drinks at the ka-local and the pothole outside your estate gate now qualifies as a crater. So you decide that it’s time you stood up and worked to make a change (also your local MP has three Prados and you want to move out of the nduthi life). You get some friends together, start pooling money, collect signatures and finally your candidacy is secure. But you’ve to pay the IEBC guy Ksh x to actually qualify, then you’ve to rent cars to take you to rallies and fuel them, also that crowd of boda boda guys and rally attendees also need a little ‘incentive’ to show their support. After the polls  ( and 20 million shillings later) you’ve received 4 votes and there’s 6 people in your household who went to the voting centre. The only thing you end up changing is your credit rating because (surprise surprise) you’re now in debt.",
  },
  {
    name: "Phone in tao",
    image: "/phoneInTao.png",
    header: "USING A PHONE IN TAO",
    body: "“Ke ke keke Wauuuu and then what did she saaaay?”  Fatuma’s story is hilarious! You can’t stop laughing and you keep asking for more details! Situational awareness is something you heard once at a self-defence class which you attended for the gym selfies, not something you practise…while walking…through a sketchy part of town. However, faster than Fatuma can say “she asked me why I was in bed with her husband”, your phone is whisked out of your hands and all you see is a young chap threading through the crowd on Moi Avenue. You lose sight of him before you even get the chance to shout “Mwizi!” ",
  },
  {
    name: "Naanza Biz",
    image: "/naanzaBiz.png",
    header: "USING A PHONE IN TAO",
    body: "“Ke ke keke Wauuuu and then what did she saaaay?”  Fatuma’s story is hilarious! You can’t stop laughing and you keep asking for more details! Situational awareness is something you heard once at a self-defence class which you attended for the gym selfies, not something you practise…while walking…through a sketchy part of town. However, faster than Fatuma can say “she asked me why I was in bed with her husband”, your phone is whisked out of your hands and all you see is a young chap threading through the crowd on Moi Avenue. You lose sight of him before you even get the chance to shout “Mwizi!” ",
  },
  {
    name: "Betting",
    image: "/betting.png",
    header: "BETTING",
    body: "Your first few bets went well. You literally doubled your money! So you get hooked, you buy ‘guaranteed bet tips’ off someone in your estate WhatsApp group, and start spreading the money around. The tips are nonsense, and you’ve lost life savings on a horse race in Bosnia and Herzegovina. Why the guy selling the tips isn't a millionaire doesn't occur to you. He seems quite content with making KSh 1000 a week from schmucks like you.",
  },
  {
    name: "Deposit on rent",
    image: "/betting.png",
    header: "BETTING",
    body: "Your first few bets went well. You literally doubled your money! So you get hooked, you buy ‘guaranteed bet tips’ off someone in your estate WhatsApp group, and start spreading the money around. The tips are nonsense, and you’ve lost life savings on a horse race in Bosnia and Herzegovina. Why the guy selling the tips isn&#39;t a millionaire doesn&#39;t occur to you. He seems quite content with making KSh 1000 a week from schmucks like you.",
  },
  {
    name: "Politician",
    image: "/politician.png",
    header: "POLITICIAN",
    body: "“He differs from the rest. This one will at least send a few tenders my way” Nah bruh! You go door to door reaching about your friend the politician. You spend money on campaign T-Shirts, help him fuel his car and even co-opt your kids to help ‌at the rallies by handing out fliers. You sing this guy’s praises more often than millennials talk about avocado toast and trans-fats. As soon as the guy gets the vote, he forgets your number. Telling his receptionist ‘you go way back’ doesn't put you through to him and his security hustle you away from him like a groupie trying to cut a lock of Beyonce’s hair. You go to your home that's still filled with “Vote Naninani T-shirts”, tender dreams in tatters and bank accounts shattered.",
  },
  {
    name: "Trusting People in the ‘Motherland’ to Build Your House",
    image: "/trust.png",
    header: "Trusting People in the ‘Motherland’ to Build Your House",
    body: "When you were 23 years old the entire village hired a matatu to take you to the airport for schooling in Amerikka. You were the first in the clan to go to university, leave alone to go study abroad! 15 years later, with a master's degree you work your ass off for 14 hours a day, and finally have enough money to invest in a house back home. Since your mother spends at least half of your weekly catch up phone call complaining about your unemployed brother, you decide he’ll be in charge of the construction. Well, there’s a reason your brother can't hold down a job. He’s a shifty character. For a year he sends you photos of the neighbours construction site claiming it’s your home. When you finally decide to visit Kenya for Christmas and check out your new home you nearly have. The construction site comprises a pile of sand, one jembe, a wheelbarrow and one half of a pair of gumboots. Your brother, just like the house,is nowhere to be seen.",
  },
  {
    name: "Please Refund/Tafadhali Nirudishie",
    image: "/refund.png",
    header: "Please Refund/Tafadhali Nirudishie",
    body: "`Hi sorry, I sent you KSh 2000 that was meant for my ailing mother in the village. Kindly send it back and may God bless you.` If you fall for this maybe you deserve to be scammed",
  },
  {
    name: "Housing agent",
    image: "/agent.png",
    header: "Housing agent",
    body: "“Mama Kwanza, it is a very lovely house, and it is on demand, even now as we speak there is another lady coming to see the house” We have heard this story at least once in our lives. The House agent insists on you paying a deposit, and his finder's fee for a house that you haven’t even seen before. Well, on moving day, you arrive at the address and find that another family moved in the day before. What’s more, behind yours there’s a pickup with another tenant in the cabin who was also supposed to move in today. The agent says he’ll refund your deposit soon…and keeps saying that for the next few months until you give up and he disappears.",
  },
  {
    name: "Corruption (Taxes)",
    image: "/coin.png",
    header: "Corruption (Taxes)",
    body: "There's a fresh scandal every week! So and so implicated in a billion shilling government swindle, that means the taxpayers (you) have been defrauded. But then again, you just paid 'Chai' to that cop who caught you in traffic while driving a car you can’t explain to KRA.",
  },
  {
    name: "Forex trading",
    image: "/forex.png",
    header: "Forex trading",
    body: "Premium tears for premium business ideas. Look at you Mr Big Man, handing over hundreds of thousands to a ‘forex trader’ who looks like someone stuffed a class 8 graduate into a kaunda suit. No wonder you’re broke.",
  },
  {
    name: "Green Houses",
    image: "/greenHouse.png",
    header: "Green Houses",
    body: "All Kenyans are cut from the same fabric unless those that aren’t. So, your buddy man Maish has 3 greenhouses that he purchased from an Israeli firm. He tells you about how much he is making…I mean he drives a moti you’ve always wanted to. So, you kopa here and there and you take your salo and put-up greenhouses. ‘Kwani iko Nini’ si Maish who is not even as smart as you is making loads of money and si its controlled farming’ You pour kedo 300k on the project…four months later you aren’t making the money the Israelite company told you, you have goods that need offloading but you didn’t research to see where the market is. So, you have produce, no market and legit farming isn’t as easy as Maish told you it would be.",
  },
  {
    name: "international con calling your number",
    image: "/conn.png",
    header: "international con calling your number",
    body: "You're sitting with your friends having a drink with a +213 number rings you.You, of course, make sure they know that it's one of your 'international clients' before you call back. You call back and after 3 minutes of hold music the line is cut and your service provider informs you ‌you've exceeded your regular post paid phone bill by Ksh 4000.",
  },
  {
    name: "Online job offers",
    image: "/online.png",
    header: "Online job offers",
    body: "You’ve sent your CV to literally every uncle that said they knew a guy, but you’re still unemployed. Your parents love you to bits but every Monday morning you can sense disappointment as they eat their breakfast ngwacis before THEY got to work and leave you at home. Then you go online on your phone (which they bought you, using data they pay for) and see a guaranteed job as a sales clerk at Naivas for an application fee of only KSh.3000! So you and every other desperate job seeker in Nairobi send in the Ksh 3000 (from mum). Two months, three days and countless calls and messages to the number of the ‘job agency’, you realise you sent your allowance to a former jobseeker. One who found a job seeking suckers like you.",
  },
  {
    name: "419 (Advance Payment Fraud)",
    image: "/fraud.png",
    header: "419 (Advance Payment Fraud)",
    body: "`My good friend, this is Doctor Alice from -insert western nation-. I'm currently in North Eastern Kenya but need to release Ksh 5 000 000 for my clinic here. They are in a locked account with a Nairobi bank. If you pay the Ksh 5000 fee and you can keep Ksh 100 000 and transfer the rest to me'",
  },
  {
    name: "Nitakurudishia next week",
    image: "/nextWeek.png",
    header: "Nitakurudishia next week",
    body: "Aki this friend is always in a fix. Sijui child is sick, sijui his mum wants to come to Nairobi from the village, so in true fashion he comes begging for money from you saying he would pay next week. Kumbe that was a story, the guy keeps telling you how much his life sucks and that he would pay you next week, for weeks until you give up.",
  },
  {
    name: "Lost ID, taking loans",
    image: "/lostId.png",
    header: "Lost ID, taking loans",
    body: "Remember last week when you lost your wallet? Well, the thieves sold your sim card to an IT student at JKUAT who registered a sim card in your name. Once again, shylocks, sketchy credit facilities and instant loan applications have received multiple applications in your name. Shortly you and your lovely sweetheart are watching telly when goons break down the door and later auction you, your bae and the TV she bought for the both of you. Ok maybe you aren't sold into slavery but you get the gist.",
  },
  {
    name: "Roadside Churches",
    image: "/roadsideChurches.png",
    header: "Roadside Churches",
    body: "You go to a roadside church (let's admit it’s a table, a PA system and I guy standing on a soda crate) You’ve had a persistent headache for two weeks and rather than see a doctor you figure the church that offers miracles for Ksh 310 is a better bet. The pastor tells you all you need is faith and a few coins to spare for your anointing oil. Anointing OIL! You get home and as you rub it on your forehead; you realise it’s cooking oil. Now you have a headache AND smell like a greasy mandazi.",
  },
  {
    name: "Mganga kutoka Tanzania",
    image: "/mganga.png",
    header: "Mganga kutoka Tanzania",
    body: "This guy and your pastor probably went to the same spiritual scam seminary. They're in the same Whatsapp group, tena they're admins. He will ask sijui for a white goat and a black chicken with red spots on its tail feathers. These he will sacrifice to the spirits of your ancestors (which likely means his wife, who has already prepped the vegetables for goat curry). And of course, a little money for him interceding with the spirits. However, your problem doesn't go away, your ex isn't suddenly in love with you/ your boss hasn't had a heart attack/ your wife's best friend is still having your baby. You’ll keep going there until it finally dawns on you ‌they have screwed you out of more domestic animals than Noah had on his ark.",
  },
  {
    name: "Mchele (and we don't mean rice)",
    image: "/mmchele.png",
    header: "Mchele (and we don't mean rice)",
    body: "The interesting thing about taking home a one-night stand is that sometimes she could rob you of everything, including your night stand. Popularly referred to as mchele, pills such as rophynol and dropped into unsuspecting mens drinks once they’ve taken a young lady of the night home. There you are, half in this world and the next and giving this stranger everything from your MPESA Pin to the DSTV child lock password. Pretty soon eve. Her mates have come over and the neighbours think you haven't paid the rent so decided to move out in the middle of the night. When you wake up everything is gone even your knock-off perfume and Rolx watches.",
  },
  {
    name: "Buying this book",
    image: "/scamBook.png",
    header: "Buying this book",
    body: "We wanted to get to forty ways to lose money but we got lazy so we decided to add the number forty. And fool you. See how easy that was. Honestly the editor thought this was a silly book and no one would buy but I guess the writer mastered the ways and got you to buy this book (insert evil laughter here)",
  },
  {
    name: "Tender",
    image: "/tender.png",
    header: "Tender",
    body: "Your friend works with the county government and can help you grab the tender to build pit latrines for some village. “Apply maze, I got you” Of course, you apply, and you get the tender because…your friend! However, after you’ve built the first latrine, your operation is at threat of grinding to a halt. - Your ‘friend’ needs a finder’s fee from you - The local MCA says that unless you grease his pockets, he’ll have the tender rescinded through the county assembly. - The local MP says that a little grease for him, they will declare your pit latrines unsafe. - The OCS says that without a little something something, items will start disappearing from your construction site. Soon you realise that after all the grease you're pouring into pockets, you’ll end up struggling to break even, leave alone make a profit.",
  },
];
